FROM node:lts-alpine3.14
LABEL maintainer="muteshi.com"

WORKDIR /app
# Install dependencies
COPY package.json .

RUN npm install --legacy-peer-deps

# Setup directory structure
COPY . .
EXPOSE 3000

CMD [ "npm","start" ]